import type { Attachment, ToolCall } from './core';

// ═══════════════════════════════════════════════════════════════════════════════
//  Conversation message types  (来自 src/tools/types/message.ts)
// ═══════════════════════════════════════════════════════════════════════════════

/** A message sent by the user. */
export type UserMessage = {
  readonly role: 'user';
  readonly content: string;
  /**
   * Optional multimodal attachments (images, PDFs, etc.) sent with this message.
   * Pass via `sendMessage(text, attachments)` or by constructing messages manually.
   * Vendor helpers (`toOpenAIMessages`, `toAnthropicMessages`, `toGeminiMessages`)
   * encode these into the correct wire format automatically.
   */
  readonly attachments?: readonly Attachment[];
};

/**
 * A message generated by the assistant, optionally including tool call requests.
 * `toolCalls` is present when the model requested one or more tool invocations.
 */
export type AssistantMessage = {
  readonly role: 'assistant';
  readonly content: string;
  readonly toolCalls?: readonly ToolCall[];
  /**
   * Chain-of-thought / reasoning text produced by thinking models
   * (DeepSeek, Doubao Seed, GLM-Z1, etc.).
   * Must be echoed back in `reasoning_content` on subsequent turns or the API
   * will reject the request with a 400 error.
   */
  readonly thinking?: string;
  /**
   * AI-generated output attachments (e.g. images produced by a generation tool).
   */
  readonly attachments?: readonly Attachment[];
};

/** The result of a tool invocation, fed back into the conversation. */
export type ToolResultMessage = {
  readonly role: 'tool';
  readonly toolCallId: string;
  readonly name: string;
  /** Serialised result returned by the tool. */
  readonly content: unknown;
  /**
   * Optional multimodal outputs from the tool (e.g. a screenshot).
   */
  readonly attachments?: readonly Attachment[];
};

/**
 * Union of all conversation message types.
 * Pass an `AgentMessage[]` array to any AI vendor API as the `messages` field.
 */
export type AgentMessage = UserMessage | AssistantMessage | ToolResultMessage;

/**
 * Controls which (if any) tool the model must call.
 *
 * - `'auto'`     — model decides whether and which tool to call (default)
 * - `'required'` — model must call at least one tool
 * - `'none'`     — model must not call any tool
 * - `{ type: 'function'; name: string }` — model must call the named tool
 */
export type ToolChoice =
  | 'auto'
  | 'required'
  | 'none'
  | { readonly type: 'function'; readonly name: string };
